languageCode = "en-us"
title = "Statistical Machine Learning Lab"
theme = "blackburn"
author = "Yoshiharu Yamashita"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  brand = "Statistical Machine Learning Lab"
  googleAnalytics = ""
  disqus = ""
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "People"
    pre = "<i class='fa fa-group fa-fw'></i>"
    weight = 3
    identifier = "people"
    url = "/people/"
  [[menu.main]]
    name = "Research"
    pre = "<i class='fa fa-cogs fa-fw'></i>"
    weight = 4
    identifier = "research"
    url = "/research/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 5
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 8
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  github = ""
  googlescholar = ""
